import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Page About",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>Movie navbar</nav>
      <main>{children}</main>
    </>
  );
}
